name: Twitch Bot
on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - name: Run bot
        run: node app.js
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_SECRET: ${{ secrets.TWITCH_SECRET }}
          CHANNEL_NAME: ${{ secrets.CHANNEL_NAME }}
      - name: Зберегти стан
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add state.json
          git commit -m "Update state" || echo "No changes to commit"
          git pull --rebase origin main || git rebase --skip
          git push origin main
